### ISSUE TITLE
Eve Online should be removed

### ISSUE THREAD

**Issue by Guddler** [trofosila/mac-on-arm#27]
**Describe the bug**
Eve Online is shown as working on M1, or 'Ready for Apple silicon' when actually all that CCP have done is announce that a native Mac version of the game client will be ready for testing in Q1 2021. In addition, it will first be released as Intel only but running on M1 under Rosetta 2. While nobody has timescales I would say it is at least 4 months too early for it to be on the list of fully native M1 games.

**Additional context**
https://maconarm.com/app/eve-online

**Comment by Guddler** [comment]
Info and FAQ from the developer: https://forums.eveonline.com/t/eve-online-to-go-native-on-macos/283578

**Comment by trofosila** [comment]
Thank you for pointing this out. I'll remove it immediately.
